---
title: "DATA 605 FUNDAMENTALS OF COMPUTATIONAL MATHEMATICS" 
subtitle: "Discussion W10: 11.1 #2"
author: "Kyle Gilde"
date: "10/18/2017"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
    toc_depth: 1
---
<style type="text/css">
body{
  font-family: Helvetica;
  font-size: 14pt;
}
</style>
<body>

```{r, echo = F}
#collapse=T, warning=FALSE
load_packages <- c("prettydoc")

#see if we need to install any of them
install_load <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
}

install_load(load_packages)
```

###2. In Example 11.4, let a = 0 and b = 1/2. Find P, P^2 , and P^3 . 

```{r}
matrix_power <- function(M, exponent) {
  ans <- M
  for (i in 1:(exponent - 1)){
    ans <- M %*% ans
    }
  return(ans)
}

a <-  0 
b  <-  1/2

d <- c(1 - a, a, b, 1 - b)
P <- matrix(d, nrow = 2, byrow = T)
row_col <- c("Yes", "No")
row.names(P) <- row_col
colnames(P) <- row_col

P; matrix_power(P, 2); matrix_power(P, 3)
```
###What would P^n be? What happens to P n as n tends to infinity? Interpret this result.
```{r}
matrix_power(P, 10000)
```

 \begin{equation}
P^n = \begin{bmatrix} 1, 0 \\
      \frac{2n - 1}{2n}, \frac{1}{2n}
      \end{bmatrix}
 \end{equation}

</body>