---
title: "DATA 605 FUNDAMENTALS OF COMPUTATIONAL MATHEMATICS" 
subtitle: "Discussion W5: 1.2 #11"
author: "Kyle Gilde"
date: "9/27/2017"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    toc: true
    toc_depth: 1
---
<style type="text/css">
body{
  font-family: Helvetica;
  font-size: 14pt;
}
</style>
<body>

```{r, echo = F}
load_packages <- c("prob")

#see if we need to install any of them
install_load <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg)) 
    install.packages(new.pkg, dependencies = TRUE)
  sapply(pkg, require, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
}

install_load(load_packages)
```

##11. What odds should a person give in favor of the following events?
(a) A card chosen at random from a 52-card deck is an ace.




###In R
```{r, collapse=T}
(Aces <- sum(cards()$rank == "A"))
(ncards <- nrow(cards()))
Aces/ncards
```

P(A) = 4/52 = 1/13
Therefore, the odds are 1:12

(b) Two heads will turn up when a coin is tossed twice.


###In R
```{r, collapse=T}

(samp_space <- tosscoin(2))

(Nsamp_space <- nrow(samp_space))
(desired_outcome <- nrow(subset(samp_space, toss1 == "H" & toss2 == "H")))

desired_outcome/Nsamp_space
```
P(A) = 1/4

Therefore, the odds are 1:3.

(c) Boxcars (two sixes) will turn up when two dice are rolled
```{r, collapse=T}
(samp_space <- rolldie(2))

(Nsamp_space <- nrow(samp_space))
(desired_outcome <- nrow(subset(samp_space, X1 == 6 & X2 == 6)))

desired_outcome/Nsamp_space
```

P(A) = 1/36
Therefore, the odds are 1:35.